name: Go-Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build -v -o ecust-library.exe
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ecust-library-windows
        path: ./ecust-library.exe
